export const autodetailingEmailTemplates = [
    { "subject": "Bring Back the Shine", "body": "Hi! Does your car need a little extra care? Let us help you restore its original brilliance." },
    { "subject": "Time to Treat Your Ride", "body": "Hello! Pamper your car with our top-notch detailing services. Reach out to schedule an appointment!" },
    { "subject": "We’re Here for Your Car Care Needs", "body": "Hi! Don’t let dirt and grime take over—contact us to keep your car looking like new!" },
    { "subject": "Your Car Deserves the Best Care", "body": "Hey there! Let’s give your car the attention it deserves with our professional detailing packages." },
    { "subject": "Say Goodbye to Dust and Dirt!", "body": "Hello! Let us handle the mess while you enjoy a spotless and shiny car." },
    { "subject": "Protect Your Investment", "body": "Hi! Regular detailing helps maintain your car’s value. Let’s book your next session!" },
    { "subject": "We Love Your Car as Much as You Do", "body": "Hey! Keep your car in pristine condition with our expert detailing services." },
    { "subject": "Summer is Here—Time to Shine!", "body": "Hi! Let’s get your car ready for those sunny drives with a comprehensive detail." },
    { "subject": "Fall is Around the Corner!", "body": "Hello! Prepare your car for the changing season with our protective detailing packages." },
    { "subject": "Winter Protection for Your Ride", "body": "Hi! Protect your car from the harsh winter elements with our premium services." },
    { "subject": "It’s Detailing Season!", "body": "Hey! Every season is a good season for a fresh, clean car—book your detail today!" },
    { "subject": "Show Your Car Some Love", "body": "Hi! Your car deserves some TLC. Let us help it look its best!" },
    { "subject": "We’re the Detailing Experts You Need", "body": "Hello! Take your car’s appearance to the next level with our professional detailing." },
    { "subject": "Don’t Let Grime Take Over", "body": "Hi! Dirt is no match for us. Let’s restore your car’s shine." },
    { "subject": "Drive in Style", "body": "Hey! A clean car is a stylish car. Let’s get yours showroom ready!" },
    { "subject": "Car Care Made Easy", "body": "Hi! We make it simple to keep your car in top shape. Contact us today!" },
    { "subject": "Restore Your Car’s Glory", "body": "Hello! Bring your car back to life with our expert detailing services." },
    { "subject": "Your Car, But Better", "body": "Hi! Let’s make your car look even better than the day you got it." },
    { "subject": "Start Fresh with a Clean Car", "body": "Hey! A fresh detail is the perfect way to start the week. Book your session now!" },
    { "subject": "Don’t Let Dirt Dull Your Ride", "body": "Hi! Keep your car looking its best with our detailing packages." },
    { "subject": "Professional Detailing at Its Best", "body": "Hello! Experience the difference a professional detail can make." },
    { "subject": "Maintain Your Car’s Value", "body": "Hi! Detailing doesn’t just clean—it protects. Let us show you how." },
    { "subject": "Drive Clean, Feel Great", "body": "Hey! A clean car makes every drive more enjoyable. Let’s make it happen!" },
    { "subject": "The Secret to a Spotless Car", "body": "Hi! Discover the power of professional detailing with us." },
    { "subject": "A Clean Car is a Happy Car", "body": "Hello! Show your car some love with our expert detailing services." },
    { "subject": "We’re Ready When You Are", "body": "Hi! Let us know when you’re ready for your next detail—we’ll take care of the rest." },
    { "subject": "Keeping Your Car Road-Ready", "body": "Hey! Let’s prepare your car for your next big adventure with a detail." },
    { "subject": "The Shine You Deserve", "body": "Hi! We’re here to bring out the best in your car. Let’s book your detail today!" },
    { "subject": "Long-Lasting Protection for Your Car", "body": "Hello! Our detailing services go beyond clean—they protect your car for the long haul." },
    { "subject": "Transform Your Drive", "body": "Hi! Make every drive feel like a new car experience with our detailing services." },
    { "subject": "Your Car’s Best Friend", "body": "Hey! Let us be your trusted partner in keeping your car pristine." },
    { "subject": "Turn Heads on the Road", "body": "Hi! Make a statement with a car that looks like it just left the showroom." },
    { "subject": "We Make Car Care Easy", "body": "Hello! Let us handle the details so you can focus on enjoying the ride." },
    { "subject": "Detailing with a Personal Touch", "body": "Hi! Our services are tailored to your car’s unique needs. Let’s get started!" },
    { "subject": "Ready to Shine?", "body": "Hey! Let us help you keep your car sparkling inside and out." },
    { "subject": "Your Car’s Best Day is One Call Away", "body": "Hi! A quick detail can make all the difference. Let’s schedule yours today!" },
    { "subject": "We’re Passionate About Cars", "body": "Hello! Let us show you how much we care with our exceptional detailing services." },
    { "subject": "Keeping You on the Road in Style", "body": "Hi! A detailed car isn’t just clean—it’s stylish. Let’s book your appointment." },
    { "subject": "Spring Clean Your Car", "body": "Hey! Spring is the perfect time for a fresh start. Let’s detail your car today!" },
    { "subject": "Your Satisfaction is Our Priority", "body": "Hi! We’re committed to making your car look its best. Let’s get to work!" },
    { "subject": "Let Us Handle the Details", "body": "Hello! From interior to exterior, we’ve got your detailing needs covered." },
    { "subject": "Make Your Car Feel New Again", "body": "Hi! Let us bring back that new car feeling with a professional detail." },
    { "subject": "Drive in Confidence", "body": "Hey! A clean car is a confident car. Let’s get yours detailed today!" },
    { "subject": "We’ve Got You Covered", "body": "Hi! Whatever your car needs, our detailing services have you covered." },
    { "subject": "Protect Your Car, Love Your Drive", "body": "Hello! Detailing protects your car and enhances every drive. Let’s book your appointment!" },
    { "subject": "Your Ride, Reimagined", "body": "Hi! Let us show you what your car is capable of with a professional detail." },
    { "subject": "Get Ready to Shine", "body": "Hey! Your car deserves to sparkle. Let’s make it happen today!" },
    { "subject": "We’re Here for You and Your Car", "body": "Hi! Let’s keep your car looking and feeling its best with our detailing services." },
    { "subject": "Attention to Every Detail", "body": "Hello! Our team is dedicated to making your car shine. Let’s get started!" },
    { "subject": "Experience the Best in Detailing", "body": "Hi! Discover the difference a professional detail can make for your car." },
    { "subject": "Your Car is in Good Hands", "body": "Hey! Trust us to care for your car as if it were our own." },
    { "subject": "Driven to Perfection", "body": "Hi! Our detailing services are designed to bring out the best in your car." },
    { "subject": "Book Your Detail Today", "body": "Hello! Don’t wait any longer—schedule your detailing appointment now!" }
]